name: 'Configuration Manager'
type: module
description: 'Allows administrators to import and export configuration changes.'
package: Core
# version: VERSION
configure: config.sync

# Information added by Drupal.org packaging script on 2021-01-07
version: '9.1.2'
project: 'drupal'
datestamp: 1609984457
